/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed':               '#ccfbf1',
        'primary-container':            '#064e3b',
        'surface-container-highest':    '#064e3b',
        'on-secondary-container':       '#dcfce7',
        'surface-container':            '#022c22',
        'background':                   '#020617',
        'inverse-primary':              '#059669',
        'on-background':                '#f8fafc',
        'secondary-fixed':              '#dcfce7',
        'surface-container-low':        '#0b1215',
        'error-container':              '#93000a',
        'surface-variant':              '#112a22',
        'secondary-fixed-dim':          '#bbf7d0',
        'inverse-surface':              '#f8fafc',
        'on-surface':                   '#f8fafc',
        'surface-bright':               '#1a4d3c',
        'on-error-container':           '#ffdad6',
        'on-error':                     '#690005',
        'on-surface-variant':           '#94a3b8',
        'secondary':                    '#2dd4bf',
        'surface-dim':                  '#020617',
        'error':                        '#ffb4ab',
        'secondary-container':          '#064e3b',
        'outline':                      '#4d7c0f',
        'on-tertiary':                  '#064e3b',
        'on-tertiary-fixed-variant':    '#064e3b',
        'on-primary':                   '#022c22',
        'surface-tint':                 '#22c55e',
        'on-primary-fixed':             '#022c22',
        'on-primary-fixed-variant':     '#064e3b',
        'inverse-on-surface':           '#022c22',
        'tertiary-container':           '#064e3b',
        'outline-variant':              '#1a4d3c',
        'primary':                      '#2dd4bf',
        'on-secondary':                 '#064e3b',
        'surface-container-lowest':     '#020617',
        'surface':                      '#020617',
        'tertiary-fixed-dim':           '#2dd4bf',
        'on-tertiary-fixed':            '#022222',
        'tertiary':                     '#10b981',
        'on-tertiary-container':        '#dcfce7',
        'on-secondary-fixed-variant':   '#065f46',
        'on-primary-container':         '#dcfce7',
        'on-secondary-fixed':           '#022c22',
        'surface-container-high':       '#0f171d',
        'primary-fixed':                '#2dd4bf',
        'primary-fixed-dim':            '#2dd4bf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
        '2xl':   '1rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      animation: {
        'pulse-slow':  'pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float':       'float 6s ease-in-out infinite',
        'star-field':  'starMovement 100s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-20px)' },
        },
        starMovement: {
          '0%':   { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-1000px)' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
